global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'x64 Linux'
    static_configs:
      - targets: ["europa.lan:9100"]
      - targets: ["dumbledore.lan:9100"]
      - targets: ["lin-proxmox-001.lan:9100"]
  - job_name: 'x64 K8s Nodes'
    static_configs:
      - targets: ["lin-kubu2204-001.lan:9100"]
      - targets: ["lin-kubu2204-002.lan:9100"]
      - targets: ["lin-kubu2204-003.lan:9100"]
  - job_name: 'Other Metrics'
    metrics_path: '/internet/metrics'
    static_configs:
      - targets: ["enviropi.lan"]
  - job_name: 'ARM Linux'
    static_configs:
      - targets: ["retropie.lan:9100"]
      - targets: ["enviropi.lan:9100"]
